# Site settings
title:
email: "minicoder@mondora.com"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/minicoder" # the subpath of your site, e.g. /blog/
url: "minicoder.it" # the base hostname & protocol for your site

ycbm_username: minicoder
github_username: mondora

# Build settings
markdown: kramdown

projects:
  data: projects